--QUERY TO FIND THE NUMBER OF FEMALE PASSENGERS WHO HAVE MADE BOOKINGS FOR AIE TICKETS.
SELECT COUNT(*) AS FEMALE_COUNT FROM AIRLINE
WHERE GENDER='Female';

--QUERY TO FIND THE TOTAL NUMBER OF PASSENGERS WHO HAVE BOOKED TICKETS IN THE BUSINESS CLASS.
SELECT COUNT(*) AS PASSENGER_COUNT FROM AIRLINE
WHERE CLASS='Business';

--QUERY TO FIND THE TOTAL NUMBER OF PASSENGERS WHO HAVE BOOKED TICKETS IN THE 'ECO' CLASS.
SELECT COUNT(*) AS ECO_PASSENGER FROM AIRLINE
WHERE CLASS='Eco';

--QUERY TO FIND THE NUMBER OF CHILDREN'S WHO ARE ALL BOOK THE TICKETS.(childrens are below Age 13).
SELECT COUNT(*) AS KID_COUNT FROM AIRLINE
WHERE AGE<13;

--QUERY TO COUNT OF PASSENGERS WHO ARE ABOVE THE AGE OF 16 AND HAVE BOOKED TICKETS IN THE BUSINESS CLASS.
SELECT COUNT(*) AS ADULT_COUNT FROM AIRLINE
WHERE AGE>16 AND CLASS='Business';